<a href="https://colab.research.google.com/github/Priyadarshan2000/30-Days-Of-Python/blob/main/Tensorflow_%2B_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu

     |████████████████████████████████| 394.3MB 43kB/s 


In [ ]:
from keras.models import load_model
from tkinter import *
import tkinter as tk
import win32gui
from PIL import ImageGrab, Image
import numpy as np

model = load_model('mnist.h5')

def predict_digit(img):
    #resize image to 28x28 pixels
    img = img.resize((28,28))
    #convert rgb to grayscale
    img = img.convert('L')
    img = np.array(img)
    #reshaping to support our model input and normalizing
    img = img.reshape(1,28,28,1)
    img = img/255.0
    #predicting the class
    res = model.predict([img])[0]
    return np.argmax(res), max(res)

class App(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)

        self.x = self.y = 0

        # Creating elements
        self.canvas = tk.Canvas(self, width=300, height=300, bg = "white", cursor="cross")
        self.label = tk.Label(self, text="Thinking..", font=("Helvetica", 48))
        self.classify_btn = tk.Button(self, text = "Recognise", command =         self.classify_handwriting) 
        self.button_clear = tk.Button(self, text = "Clear", command = self.clear_all)

        # Grid structure
        self.canvas.grid(row=0, column=0, pady=2, sticky=W, )
        self.label.grid(row=0, column=1,pady=2, padx=2)
        self.classify_btn.grid(row=1, column=1, pady=2, padx=2)
        self.button_clear.grid(row=1, column=0, pady=2)

        #self.canvas.bind("<Motion>", self.start_pos)
        self.canvas.bind("<B1-Motion>", self.draw_lines)

    def clear_all(self):
        self.canvas.delete("all")

    def classify_handwriting(self):
        HWND = self.canvas.winfo_id() # get the handle of the canvas
        rect = win32gui.GetWindowRect(HWND) # get the coordinate of the canvas
        im = ImageGrab.grab(rect)

        digit, acc = predict_digit(im)
        self.label.configure(text= str(digit)+', '+ str(int(acc*100))+'%')

    def draw_lines(self, event):
        self.x = event.x
        self.y = event.y
        r=8
        self.canvas.create_oval(self.x-r, self.y-r, self.x + r, self.y + r, fill='black')

app = App()
mainloop()

ModuleNotFoundError: ignored

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
import tensorflow as tf
r1_decimal = tf.constant(1.12345, tf.float32)
print(r1_decimal)
# String
r1_string = tf.constant("tensorflow", tf.string)
print(r1_string)

tf.Tensor(1.12345, shape=(), dtype=float32)
tf.Tensor(b'tensorflow', shape=(), dtype=string)


In [ ]:
# 2D martix
import tensorflow as tf
r2_matrix = tf.constant([ [1, 2],
                          [3, 4] ],tf.int16)
print(r2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [ ]:
import tensorflow as tf
r2 = tf.constant(1, tf.int16, name = "my_scalar") 
print(r2)

tf.Tensor(1, shape=(), dtype=int16)


In [ ]:
# main list (sub list (small element ))
import tensorflow as tf
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)
print(r3_matrix)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)


In [ ]:
import tensorflow as tf
type_float = tf.constant(3.123456789, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)
print(type_float.dtype)
print(type_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


In [ ]:
# add in tensorflow
import tensorflow as tf
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [ ]:
# multiply(normal) in tensorflow
import tensorflow as tf
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [ ]:
import tensorflow as tf
x = tf.constant([2])
y = tf.constant([4])
z=tf.multiply(x,y)
print(z)

tf.Tensor([8], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
# Create a 2x2 matrixtensor_const = tf.constant([[10, 20], [30, 40]])
# Initialize the first value of the tensor equals to tensor_const
var_init_2 = tf.get_variable("var_init_2", dtype=tf.int32,  initializer=tensor_const)
print(var_init_2.shape)

AttributeError: ignored

In [ ]:
import tensorflow as tf
sess = tf.Session() 
result = sess.run(multiply)
print(result)
sess.close()

AttributeError: ignored

In [ ]:
import tensorflow as tf
x = tf.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
z = tf.get_variable("z", dtype=tf.int32,  initializer=tf.constant([6]))
c = tf.constant([5], name =	"constant")square = tf.constant([2], name =	"square")
f = tf.multiply(x, z) + tf.pow(x, square) + z + c

SyntaxError: ignored

In [ ]:
 from keras import backend as k
 k.backend()

'tensorflow'

In [ ]:
import keras as k
data = k.placeholder(shape = (1,3,3)) 

AttributeError: ignored

In [ ]:
from keras.models import Sequential 
from keras.layers import Dense, Activation 

model = Sequential()  
model.add(Dense(512, activation = 'relu', input_shape = (784,)))
print(model)

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
dataset = loadtxt('/content/diabetes.csv', delimiter=',')
X = dataset[:,0:8]
y = dataset[:,8]

ValueError: ignored

In [ ]:
import sys
from PyQt5 import QtGui

def window():
   app = QtGui.QApplication(sys.argv)
   w = QtGui.QWidget()
   b = QtGui.QLabel(w)
   b.setText("Hello World!")
   w.setGeometry(100,100,200,50)
   b.move(50,20)
   #w.setWindowTitle(“PyQt”)
   w.show()
   sys.exit(app.exec_())
	
if __name__ == '__main__':
   window()

ModuleNotFoundError: ignored

In [ ]:
import pyperclip 

pyperclip.copy("Hello world !") 
pyperclip.paste() 

  

pyperclip.copy("Isn't pyperclip interesting?") 
pyperclip.paste()

PyperclipException: ignored

In [ ]:
from emoji import emojize 

print(emojize(":snake:"))

🐍


In [ ]:
import pyperclip 

pyperclip.copy("Hello world !") 
pyperclip.paste() 

  

pyperclip.copy("Isn't pyperclip interesting?") 
pyperclip.paste()

PyperclipException: ignored